package debug

import (
	"fmt"
)

var instructions [256]Instruction
var bitInstructions [256]Instruction

type Instruction struct {
	OP          string
	Len         int
	Jump        bool
	Conditional bool
	Relative    bool
	Stop        bool
}

type DecodedInsturction struct {
	Instruction
	Addr    uint16
	HasData bool
	Data    uint16
}

func (d DecodedInsturction) String() string {
	if d.Relative {
		return fmt.Sprintf(d.OP, uint16(int(d.Addr)+2+int(int8(d.Data))))
	}
	if d.Len > 1 && d.HasData {
		return fmt.Sprintf(d.OP, d.Data)
	}
	return d.OP
}

func init() {
	instructions = [256]Instruction{
		Instruction{OP: "NOP", Len: 1},
		Instruction{OP: "LD BC,$%04X", Len: 3},
		Instruction{OP: "LD (BC),A", Len: 1},
		Instruction{OP: "INC BC", Len: 1},
		Instruction{OP: "INC B", Len: 1},
		Instruction{OP: "DEC B", Len: 1},
		Instruction{OP: "LD B,$%02X", Len: 2},
		Instruction{OP: "RLC A", Len: 1},
		Instruction{OP: "LD ($%04X),SP", Len: 3},
		Instruction{OP: "ADD HL,BC", Len: 1},
		Instruction{OP: "LD A,(BC)", Len: 1},
		Instruction{OP: "DEC BC", Len: 1},
		Instruction{OP: "INC C", Len: 1},
		Instruction{OP: "DEC C", Len: 1},
		Instruction{OP: "LD C,$%02X", Len: 2},
		Instruction{OP: "RRC A", Len: 1},
		Instruction{OP: "STOP", Len: 1, Stop: true},
		Instruction{OP: "LD DE,$%04X", Len: 3},
		Instruction{OP: "LD (DE),A", Len: 1},
		Instruction{OP: "INC DE", Len: 1},
		Instruction{OP: "INC D", Len: 1},
		Instruction{OP: "DEC D", Len: 1},
		Instruction{OP: "LD D,$%02X", Len: 2},
		Instruction{OP: "RL A", Len: 1},
		Instruction{OP: "JR $%04X", Len: 2, Jump: true, Relative: true},
		Instruction{OP: "ADD HL,DE", Len: 1},
		Instruction{OP: "LD A,(DE)", Len: 1},
		Instruction{OP: "DEC DE", Len: 1},
		Instruction{OP: "INC E", Len: 1},
		Instruction{OP: "DEC E", Len: 1},
		Instruction{OP: "LD E,$%02X", Len: 2},
		Instruction{OP: "RR A", Len: 1},
		Instruction{OP: "JR NZ,$%04X", Len: 2, Jump: true, Conditional: true, Relative: true},
		Instruction{OP: "LD HL,$%04X", Len: 3},
		Instruction{OP: "LDI (HL),A", Len: 1},
		Instruction{OP: "INC HL", Len: 1},
		Instruction{OP: "INC H", Len: 1},
		Instruction{OP: "DEC H", Len: 1},
		Instruction{OP: "LD H,$%02X", Len: 2},
		Instruction{OP: "DAA", Len: 1},
		Instruction{OP: "JR Z,$%04X", Len: 2, Jump: true, Conditional: true, Relative: true},
		Instruction{OP: "ADD HL,HL", Len: 1},
		Instruction{OP: "LDI A,(HL)", Len: 1},
		Instruction{OP: "DEC HL", Len: 1},
		Instruction{OP: "INC L", Len: 1},
		Instruction{OP: "DEC L", Len: 1},
		Instruction{OP: "LD L,$%02X", Len: 2},
		Instruction{OP: "CPL", Len: 1},
		Instruction{OP: "JR NC,$%04X", Len: 2, Jump: true, Conditional: true, Relative: true},
		Instruction{OP: "LD SP,$%04X", Len: 3},
		Instruction{OP: "LDD (HL),A", Len: 1},
		Instruction{OP: "INC SP", Len: 1},
		Instruction{OP: "INC (HL)", Len: 1},
		Instruction{OP: "DEC (HL)", Len: 1},
		Instruction{OP: "LD (HL),$%02X", Len: 2},
		Instruction{OP: "SCF", Len: 1},
		Instruction{OP: "JR C,$%04X", Len: 2, Jump: true, Conditional: true, Relative: true},
		Instruction{OP: "ADD HL,SP", Len: 1},
		Instruction{OP: "LDD A,(HL)", Len: 1},
		Instruction{OP: "DEC SP", Len: 1},
		Instruction{OP: "INC A", Len: 1},
		Instruction{OP: "DEC A", Len: 1},
		Instruction{OP: "LD A,$%02X", Len: 2},
		Instruction{OP: "CCF", Len: 1},
		Instruction{OP: "LD B,B", Len: 1},
		Instruction{OP: "LD B,C", Len: 1},
		Instruction{OP: "LD B,D", Len: 1},
		Instruction{OP: "LD B,E", Len: 1},
		Instruction{OP: "LD B,H", Len: 1},
		Instruction{OP: "LD B,L", Len: 1},
		Instruction{OP: "LD B,(HL)", Len: 1},
		Instruction{OP: "LD B,A", Len: 1},
		Instruction{OP: "LD C,B", Len: 1},
		Instruction{OP: "LD C,C", Len: 1},
		Instruction{OP: "LD C,D", Len: 1},
		Instruction{OP: "LD C,E", Len: 1},
		Instruction{OP: "LD C,H", Len: 1},
		Instruction{OP: "LD C,L", Len: 1},
		Instruction{OP: "LD C,(HL)", Len: 1},
		Instruction{OP: "LD C,A", Len: 1},
		Instruction{OP: "LD D,B", Len: 1},
		Instruction{OP: "LD D,C", Len: 1},
		Instruction{OP: "LD D,D", Len: 1},
		Instruction{OP: "LD D,E", Len: 1},
		Instruction{OP: "LD D,H", Len: 1},
		Instruction{OP: "LD D,L", Len: 1},
		Instruction{OP: "LD D,(HL)", Len: 1},
		Instruction{OP: "LD D,A", Len: 1},
		Instruction{OP: "LD E,B", Len: 1},
		Instruction{OP: "LD E,C", Len: 1},
		Instruction{OP: "LD E,D", Len: 1},
		Instruction{OP: "LD E,E", Len: 1},
		Instruction{OP: "LD E,H", Len: 1},
		Instruction{OP: "LD E,L", Len: 1},
		Instruction{OP: "LD E,(HL)", Len: 1},
		Instruction{OP: "LD E,A", Len: 1},
		Instruction{OP: "LD H,B", Len: 1},
		Instruction{OP: "LD H,C", Len: 1},
		Instruction{OP: "LD H,D", Len: 1},
		Instruction{OP: "LD H,E", Len: 1},
		Instruction{OP: "LD H,H", Len: 1},
		Instruction{OP: "LD H,L", Len: 1},
		Instruction{OP: "LD H,(HL)", Len: 1},
		Instruction{OP: "LD H,A", Len: 1},
		Instruction{OP: "LD L,B", Len: 1},
		Instruction{OP: "LD L,C", Len: 1},
		Instruction{OP: "LD L,D", Len: 1},
		Instruction{OP: "LD L,E", Len: 1},
		Instruction{OP: "LD L,H", Len: 1},
		Instruction{OP: "LD L,L", Len: 1},
		Instruction{OP: "LD L,(HL)", Len: 1},
		Instruction{OP: "LD L,A", Len: 1},
		Instruction{OP: "LD (HL),B", Len: 1},
		Instruction{OP: "LD (HL),C", Len: 1},
		Instruction{OP: "LD (HL),D", Len: 1},
		Instruction{OP: "LD (HL),E", Len: 1},
		Instruction{OP: "LD (HL),H", Len: 1},
		Instruction{OP: "LD (HL),L", Len: 1},
		Instruction{OP: "HALT", Len: 1},
		Instruction{OP: "LD (HL),A", Len: 1},
		Instruction{OP: "LD A,B", Len: 1},
		Instruction{OP: "LD A,C", Len: 1},
		Instruction{OP: "LD A,D", Len: 1},
		Instruction{OP: "LD A,E", Len: 1},
		Instruction{OP: "LD A,H", Len: 1},
		Instruction{OP: "LD A,L", Len: 1},
		Instruction{OP: "LD A,(HL)", Len: 1},
		Instruction{OP: "LD A,A", Len: 1},
		Instruction{OP: "ADD A,B", Len: 1},
		Instruction{OP: "ADD A,C", Len: 1},
		Instruction{OP: "ADD A,D", Len: 1},
		Instruction{OP: "ADD A,E", Len: 1},
		Instruction{OP: "ADD A,H", Len: 1},
		Instruction{OP: "ADD A,L", Len: 1},
		Instruction{OP: "ADD A,(HL)", Len: 1},
		Instruction{OP: "ADD A,A", Len: 1},
		Instruction{OP: "ADC A,B", Len: 1},
		Instruction{OP: "ADC A,C", Len: 1},
		Instruction{OP: "ADC A,D", Len: 1},
		Instruction{OP: "ADC A,E", Len: 1},
		Instruction{OP: "ADC A,H", Len: 1},
		Instruction{OP: "ADC A,L", Len: 1},
		Instruction{OP: "ADC A,(HL)", Len: 1},
		Instruction{OP: "ADC A,A", Len: 1},
		Instruction{OP: "SUB A,B", Len: 1},
		Instruction{OP: "SUB A,C", Len: 1},
		Instruction{OP: "SUB A,D", Len: 1},
		Instruction{OP: "SUB A,E", Len: 1},
		Instruction{OP: "SUB A,H", Len: 1},
		Instruction{OP: "SUB A,L", Len: 1},
		Instruction{OP: "SUB A,(HL)", Len: 1},
		Instruction{OP: "SUB A,A", Len: 1},
		Instruction{OP: "SBC A,B", Len: 1},
		Instruction{OP: "SBC A,C", Len: 1},
		Instruction{OP: "SBC A,D", Len: 1},
		Instruction{OP: "SBC A,E", Len: 1},
		Instruction{OP: "SBC A,H", Len: 1},
		Instruction{OP: "SBC A,L", Len: 1},
		Instruction{OP: "SBC A,(HL)", Len: 1},
		Instruction{OP: "SBC A,A", Len: 1},
		Instruction{OP: "AND B", Len: 1},
		Instruction{OP: "AND C", Len: 1},
		Instruction{OP: "AND D", Len: 1},
		Instruction{OP: "AND E", Len: 1},
		Instruction{OP: "AND H", Len: 1},
		Instruction{OP: "AND L", Len: 1},
		Instruction{OP: "AND (HL)", Len: 1},
		Instruction{OP: "AND A", Len: 1},
		Instruction{OP: "XOR B", Len: 1},
		Instruction{OP: "XOR C", Len: 1},
		Instruction{OP: "XOR D", Len: 1},
		Instruction{OP: "XOR E", Len: 1},
		Instruction{OP: "XOR H", Len: 1},
		Instruction{OP: "XOR L", Len: 1},
		Instruction{OP: "XOR (HL)", Len: 1},
		Instruction{OP: "XOR A", Len: 1},
		Instruction{OP: "OR B", Len: 1},
		Instruction{OP: "OR C", Len: 1},
		Instruction{OP: "OR D", Len: 1},
		Instruction{OP: "OR E", Len: 1},
		Instruction{OP: "OR H", Len: 1},
		Instruction{OP: "OR L", Len: 1},
		Instruction{OP: "OR (HL)", Len: 1},
		Instruction{OP: "OR A", Len: 1},
		Instruction{OP: "CP B", Len: 1},
		Instruction{OP: "CP C", Len: 1},
		Instruction{OP: "CP D", Len: 1},
		Instruction{OP: "CP E", Len: 1},
		Instruction{OP: "CP H", Len: 1},
		Instruction{OP: "CP L", Len: 1},
		Instruction{OP: "CP (HL)", Len: 1},
		Instruction{OP: "CP A", Len: 1},
		Instruction{OP: "RET NZ", Len: 1},
		Instruction{OP: "POP BC", Len: 1},
		Instruction{OP: "JP NZ,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "JP $%04X", Len: 3, Jump: true},
		Instruction{OP: "CALL NZ,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "PUSH BC", Len: 1},
		Instruction{OP: "ADD A,$%02X", Len: 2},
		Instruction{OP: "RST 0", Len: 1},
		Instruction{OP: "RET Z", Len: 1},
		Instruction{OP: "RET", Len: 1, Stop: true},
		Instruction{OP: "JP Z,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "Ext ops", Len: 1},
		Instruction{OP: "CALL Z,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "CALL $%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "ADC A,$%02X", Len: 2},
		Instruction{OP: "RST 8", Len: 1},
		Instruction{OP: "RET NC", Len: 1},
		Instruction{OP: "POP DE", Len: 1},
		Instruction{OP: "JP NC,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "CALL NC,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "PUSH DE", Len: 1},
		Instruction{OP: "SUB A,$%02X", Len: 2},
		Instruction{OP: "RST 10", Len: 1},
		Instruction{OP: "RET C", Len: 1},
		Instruction{OP: "RETI", Len: 1},
		Instruction{OP: "JP C,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "CALL C,$%04X", Len: 3, Jump: true, Conditional: true},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "SBC A,$%02X", Len: 2},
		Instruction{OP: "RST 18", Len: 1},
		Instruction{OP: "LDH ($%02X),A", Len: 2},
		Instruction{OP: "POP HL", Len: 1},
		Instruction{OP: "LDH (C),A", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "PUSH HL", Len: 1},
		Instruction{OP: "AND $%02X", Len: 2},
		Instruction{OP: "RST 20", Len: 1},
		Instruction{OP: "ADD SP,d", Len: 1},
		Instruction{OP: "JP (HL)", Len: 1, Jump: true},
		Instruction{OP: "LD ($%02X),A", Len: 3},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "XOR $%02X", Len: 2},
		Instruction{OP: "RST 28", Len: 1},
		Instruction{OP: "LDH A,($%02X)", Len: 2},
		Instruction{OP: "POP AF", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "DI", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "PUSH AF", Len: 1},
		Instruction{OP: "OR $%02X", Len: 2},
		Instruction{OP: "RST 30", Len: 1},
		Instruction{OP: "LD HL,SP+%02X", Len: 2},
		Instruction{OP: "LD SP,HL", Len: 1},
		Instruction{OP: "LD A,($%04X)", Len: 3},
		Instruction{OP: "EI", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "XX", Len: 1},
		Instruction{OP: "CP $%02X", Len: 2},
		Instruction{OP: "RST 38", Len: 1},
	}
	bitInstructions = [256]Instruction{
		Instruction{OP: "RLC B", Len: 2},
		Instruction{OP: "RLC C", Len: 2},
		Instruction{OP: "RLC D", Len: 2},
		Instruction{OP: "RLC E", Len: 2},
		Instruction{OP: "RLC H", Len: 2},
		Instruction{OP: "RLC L", Len: 2},
		Instruction{OP: "RLC (HL)", Len: 2},
		Instruction{OP: "RLC A", Len: 2},
		Instruction{OP: "RRC B", Len: 2},
		Instruction{OP: "RRC C", Len: 2},
		Instruction{OP: "RRC D", Len: 2},
		Instruction{OP: "RRC E", Len: 2},
		Instruction{OP: "RRC H", Len: 2},
		Instruction{OP: "RRC L", Len: 2},
		Instruction{OP: "RRC (HL)", Len: 2},
		Instruction{OP: "RRC A", Len: 2},
		Instruction{OP: "RL B", Len: 2},
		Instruction{OP: "RL C", Len: 2},
		Instruction{OP: "RL D", Len: 2},
		Instruction{OP: "RL E", Len: 2},
		Instruction{OP: "RL H", Len: 2},
		Instruction{OP: "RL L", Len: 2},
		Instruction{OP: "RL (HL)", Len: 2},
		Instruction{OP: "RL A", Len: 2},
		Instruction{OP: "RR B", Len: 2},
		Instruction{OP: "RR C", Len: 2},
		Instruction{OP: "RR D", Len: 2},
		Instruction{OP: "RR E", Len: 2},
		Instruction{OP: "RR H", Len: 2},
		Instruction{OP: "RR L", Len: 2},
		Instruction{OP: "RR (HL)", Len: 2},
		Instruction{OP: "RR A", Len: 2},
		Instruction{OP: "SLA B", Len: 2},
		Instruction{OP: "SLA C", Len: 2},
		Instruction{OP: "SLA D", Len: 2},
		Instruction{OP: "SLA E", Len: 2},
		Instruction{OP: "SLA H", Len: 2},
		Instruction{OP: "SLA L", Len: 2},
		Instruction{OP: "SLA (HL)", Len: 2},
		Instruction{OP: "SLA A", Len: 2},
		Instruction{OP: "SRA B", Len: 2},
		Instruction{OP: "SRA C", Len: 2},
		Instruction{OP: "SRA D", Len: 2},
		Instruction{OP: "SRA E", Len: 2},
		Instruction{OP: "SRA H", Len: 2},
		Instruction{OP: "SRA L", Len: 2},
		Instruction{OP: "SRA (HL)", Len: 2},
		Instruction{OP: "SRA A", Len: 2},
		Instruction{OP: "SWAP B", Len: 2},
		Instruction{OP: "SWAP C", Len: 2},
		Instruction{OP: "SWAP D", Len: 2},
		Instruction{OP: "SWAP E", Len: 2},
		Instruction{OP: "SWAP H", Len: 2},
		Instruction{OP: "SWAP L", Len: 2},
		Instruction{OP: "SWAP (HL)", Len: 2},
		Instruction{OP: "SWAP A", Len: 2},
		Instruction{OP: "SRL B", Len: 2},
		Instruction{OP: "SRL C", Len: 2},
		Instruction{OP: "SRL D", Len: 2},
		Instruction{OP: "SRL E", Len: 2},
		Instruction{OP: "SRL H", Len: 2},
		Instruction{OP: "SRL L", Len: 2},
		Instruction{OP: "SRL (HL)", Len: 2},
		Instruction{OP: "SRL A", Len: 2},
		Instruction{OP: "BIT 0,B", Len: 2},
		Instruction{OP: "BIT 0,C", Len: 2},
		Instruction{OP: "BIT 0,D", Len: 2},
		Instruction{OP: "BIT 0,E", Len: 2},
		Instruction{OP: "BIT 0,H", Len: 2},
		Instruction{OP: "BIT 0,L", Len: 2},
		Instruction{OP: "BIT 0,(HL)", Len: 2},
		Instruction{OP: "BIT 0,A", Len: 2},
		Instruction{OP: "BIT 1,B", Len: 2},
		Instruction{OP: "BIT 1,C", Len: 2},
		Instruction{OP: "BIT 1,D", Len: 2},
		Instruction{OP: "BIT 1,E", Len: 2},
		Instruction{OP: "BIT 1,H", Len: 2},
		Instruction{OP: "BIT 1,L", Len: 2},
		Instruction{OP: "BIT 1,(HL)", Len: 2},
		Instruction{OP: "BIT 1,A", Len: 2},
		Instruction{OP: "BIT 2,B", Len: 2},
		Instruction{OP: "BIT 2,C", Len: 2},
		Instruction{OP: "BIT 2,D", Len: 2},
		Instruction{OP: "BIT 2,E", Len: 2},
		Instruction{OP: "BIT 2,H", Len: 2},
		Instruction{OP: "BIT 2,L", Len: 2},
		Instruction{OP: "BIT 2,(HL)", Len: 2},
		Instruction{OP: "BIT 2,A", Len: 2},
		Instruction{OP: "BIT 3,B", Len: 2},
		Instruction{OP: "BIT 3,C", Len: 2},
		Instruction{OP: "BIT 3,D", Len: 2},
		Instruction{OP: "BIT 3,E", Len: 2},
		Instruction{OP: "BIT 3,H", Len: 2},
		Instruction{OP: "BIT 3,L", Len: 2},
		Instruction{OP: "BIT 3,(HL)", Len: 2},
		Instruction{OP: "BIT 3,A", Len: 2},
		Instruction{OP: "BIT 4,B", Len: 2},
		Instruction{OP: "BIT 4,C", Len: 2},
		Instruction{OP: "BIT 4,D", Len: 2},
		Instruction{OP: "BIT 4,E", Len: 2},
		Instruction{OP: "BIT 4,H", Len: 2},
		Instruction{OP: "BIT 4,L", Len: 2},
		Instruction{OP: "BIT 4,(HL)", Len: 2},
		Instruction{OP: "BIT 4,A", Len: 2},
		Instruction{OP: "BIT 5,B", Len: 2},
		Instruction{OP: "BIT 5,C", Len: 2},
		Instruction{OP: "BIT 5,D", Len: 2},
		Instruction{OP: "BIT 5,E", Len: 2},
		Instruction{OP: "BIT 5,H", Len: 2},
		Instruction{OP: "BIT 5,L", Len: 2},
		Instruction{OP: "BIT 5,(HL)", Len: 2},
		Instruction{OP: "BIT 5,A", Len: 2},
		Instruction{OP: "BIT 6,B", Len: 2},
		Instruction{OP: "BIT 6,C", Len: 2},
		Instruction{OP: "BIT 6,D", Len: 2},
		Instruction{OP: "BIT 6,E", Len: 2},
		Instruction{OP: "BIT 6,H", Len: 2},
		Instruction{OP: "BIT 6,L", Len: 2},
		Instruction{OP: "BIT 6,(HL)", Len: 2},
		Instruction{OP: "BIT 6,A", Len: 2},
		Instruction{OP: "BIT 7,B", Len: 2},
		Instruction{OP: "BIT 7,C", Len: 2},
		Instruction{OP: "BIT 7,D", Len: 2},
		Instruction{OP: "BIT 7,E", Len: 2},
		Instruction{OP: "BIT 7,H", Len: 2},
		Instruction{OP: "BIT 7,L", Len: 2},
		Instruction{OP: "BIT 7,(HL)", Len: 2},
		Instruction{OP: "BIT 7,A", Len: 2},
		Instruction{OP: "RES 0,B", Len: 2},
		Instruction{OP: "RES 0,C", Len: 2},
		Instruction{OP: "RES 0,D", Len: 2},
		Instruction{OP: "RES 0,E", Len: 2},
		Instruction{OP: "RES 0,H", Len: 2},
		Instruction{OP: "RES 0,L", Len: 2},
		Instruction{OP: "RES 0,(HL)", Len: 2},
		Instruction{OP: "RES 0,A", Len: 2},
		Instruction{OP: "RES 1,B", Len: 2},
		Instruction{OP: "RES 1,C", Len: 2},
		Instruction{OP: "RES 1,D", Len: 2},
		Instruction{OP: "RES 1,E", Len: 2},
		Instruction{OP: "RES 1,H", Len: 2},
		Instruction{OP: "RES 1,L", Len: 2},
		Instruction{OP: "RES 1,(HL)", Len: 2},
		Instruction{OP: "RES 1,A", Len: 2},
		Instruction{OP: "RES 2,B", Len: 2},
		Instruction{OP: "RES 2,C", Len: 2},
		Instruction{OP: "RES 2,D", Len: 2},
		Instruction{OP: "RES 2,E", Len: 2},
		Instruction{OP: "RES 2,H", Len: 2},
		Instruction{OP: "RES 2,L", Len: 2},
		Instruction{OP: "RES 2,(HL)", Len: 2},
		Instruction{OP: "RES 2,A", Len: 2},
		Instruction{OP: "RES 3,B", Len: 2},
		Instruction{OP: "RES 3,C", Len: 2},
		Instruction{OP: "RES 3,D", Len: 2},
		Instruction{OP: "RES 3,E", Len: 2},
		Instruction{OP: "RES 3,H", Len: 2},
		Instruction{OP: "RES 3,L", Len: 2},
		Instruction{OP: "RES 3,(HL)", Len: 2},
		Instruction{OP: "RES 3,A", Len: 2},
		Instruction{OP: "RES 4,B", Len: 2},
		Instruction{OP: "RES 4,C", Len: 2},
		Instruction{OP: "RES 4,D", Len: 2},
		Instruction{OP: "RES 4,E", Len: 2},
		Instruction{OP: "RES 4,H", Len: 2},
		Instruction{OP: "RES 4,L", Len: 2},
		Instruction{OP: "RES 4,(HL)", Len: 2},
		Instruction{OP: "RES 4,A", Len: 2},
		Instruction{OP: "RES 5,B", Len: 2},
		Instruction{OP: "RES 5,C", Len: 2},
		Instruction{OP: "RES 5,D", Len: 2},
		Instruction{OP: "RES 5,E", Len: 2},
		Instruction{OP: "RES 5,H", Len: 2},
		Instruction{OP: "RES 5,L", Len: 2},
		Instruction{OP: "RES 5,(HL)", Len: 2},
		Instruction{OP: "RES 5,A", Len: 2},
		Instruction{OP: "RES 6,B", Len: 2},
		Instruction{OP: "RES 6,C", Len: 2},
		Instruction{OP: "RES 6,D", Len: 2},
		Instruction{OP: "RES 6,E", Len: 2},
		Instruction{OP: "RES 6,H", Len: 2},
		Instruction{OP: "RES 6,L", Len: 2},
		Instruction{OP: "RES 6,(HL)", Len: 2},
		Instruction{OP: "RES 6,A", Len: 2},
		Instruction{OP: "RES 7,B", Len: 2},
		Instruction{OP: "RES 7,C", Len: 2},
		Instruction{OP: "RES 7,D", Len: 2},
		Instruction{OP: "RES 7,E", Len: 2},
		Instruction{OP: "RES 7,H", Len: 2},
		Instruction{OP: "RES 7,L", Len: 2},
		Instruction{OP: "RES 7,(HL)", Len: 2},
		Instruction{OP: "RES 7,A", Len: 2},
		Instruction{OP: "SET 0,B", Len: 2},
		Instruction{OP: "SET 0,C", Len: 2},
		Instruction{OP: "SET 0,D", Len: 2},
		Instruction{OP: "SET 0,E", Len: 2},
		Instruction{OP: "SET 0,H", Len: 2},
		Instruction{OP: "SET 0,L", Len: 2},
		Instruction{OP: "SET 0,(HL)", Len: 2},
		Instruction{OP: "SET 0,A", Len: 2},
		Instruction{OP: "SET 1,B", Len: 2},
		Instruction{OP: "SET 1,C", Len: 2},
		Instruction{OP: "SET 1,D", Len: 2},
		Instruction{OP: "SET 1,E", Len: 2},
		Instruction{OP: "SET 1,H", Len: 2},
		Instruction{OP: "SET 1,L", Len: 2},
		Instruction{OP: "SET 1,(HL)", Len: 2},
		Instruction{OP: "SET 1,A", Len: 2},
		Instruction{OP: "SET 2,B", Len: 2},
		Instruction{OP: "SET 2,C", Len: 2},
		Instruction{OP: "SET 2,D", Len: 2},
		Instruction{OP: "SET 2,E", Len: 2},
		Instruction{OP: "SET 2,H", Len: 2},
		Instruction{OP: "SET 2,L", Len: 2},
		Instruction{OP: "SET 2,(HL)", Len: 2},
		Instruction{OP: "SET 2,A", Len: 2},
		Instruction{OP: "SET 3,B", Len: 2},
		Instruction{OP: "SET 3,C", Len: 2},
		Instruction{OP: "SET 3,D", Len: 2},
		Instruction{OP: "SET 3,E", Len: 2},
		Instruction{OP: "SET 3,H", Len: 2},
		Instruction{OP: "SET 3,L", Len: 2},
		Instruction{OP: "SET 3,(HL)", Len: 2},
		Instruction{OP: "SET 3,A", Len: 2},
		Instruction{OP: "SET 4,B", Len: 2},
		Instruction{OP: "SET 4,C", Len: 2},
		Instruction{OP: "SET 4,D", Len: 2},
		Instruction{OP: "SET 4,E", Len: 2},
		Instruction{OP: "SET 4,H", Len: 2},
		Instruction{OP: "SET 4,L", Len: 2},
		Instruction{OP: "SET 4,(HL)", Len: 2},
		Instruction{OP: "SET 4,A", Len: 2},
		Instruction{OP: "SET 5,B", Len: 2},
		Instruction{OP: "SET 5,C", Len: 2},
		Instruction{OP: "SET 5,D", Len: 2},
		Instruction{OP: "SET 5,E", Len: 2},
		Instruction{OP: "SET 5,H", Len: 2},
		Instruction{OP: "SET 5,L", Len: 2},
		Instruction{OP: "SET 5,(HL)", Len: 2},
		Instruction{OP: "SET 5,A", Len: 2},
		Instruction{OP: "SET 6,B", Len: 2},
		Instruction{OP: "SET 6,C", Len: 2},
		Instruction{OP: "SET 6,D", Len: 2},
		Instruction{OP: "SET 6,E", Len: 2},
		Instruction{OP: "SET 6,H", Len: 2},
		Instruction{OP: "SET 6,L", Len: 2},
		Instruction{OP: "SET 6,(HL)", Len: 2},
		Instruction{OP: "SET 6,A", Len: 2},
		Instruction{OP: "SET 7,B", Len: 2},
		Instruction{OP: "SET 7,C", Len: 2},
		Instruction{OP: "SET 7,D", Len: 2},
		Instruction{OP: "SET 7,E", Len: 2},
		Instruction{OP: "SET 7,H", Len: 2},
		Instruction{OP: "SET 7,L", Len: 2},
		Instruction{OP: "SET 7,(HL)", Len: 2},
		Instruction{OP: "SET 7,A", Len: 2},
	}
}
